# https://phptoday.ru/post/gotovim-lokalnuyu-sredu-docker-dlya-razrabotki-na-php
# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    nginx:
        container_name: nginx
        # используем последний стабильный образ nginx
        image: nginx:latest
        networks:
            application_nerwork:
                ipv4_address: 172.18.18.2
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        container_name: php
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        networks:
            application_nerwork:
                ipv4_address: 172.18.18.3
        # этот образ будет общаться с mysql
        links:
            - mariadb
        depends_on:
            - mariadb
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    mariadb:
        container_name: mariadb
        image: mariadb:10.3
        expose:
            - 3312
        networks:
            application_nerwork:
                ipv4_address: 172.18.18.4
        ports:
          - 3312:3306
        volumes:
          - ./mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password_security
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        networks:
            application_nerwork:
                ipv4_address: 172.18.18.5
        ports:
          - 8765:80
        environment:
            MYSQL_ROOT_PASSWORD: root_password_security
        links:
          - mariadb:db
        depends_on:
          - mariadb

networks:
    application_nerwork:
        driver: bridge
        driver_opts:
          com.docker.network.enable_ipv6: "false"
        ipam:
          driver: default
          config:
          - subnet: 172.18.18.0/24
            gateway: 172.18.18.1
